### ISSUE TITLE
שטריך בעטן מה קוראים אותו דרישתא לפיצוריא

### ISSUE THREAD

**Issue by abiller** [hezylaplacian/basadify#1]
מניין מוסיפין תמיכה למיני ברכות הנהוגות בק"ק טרייענז?

**Comment by hezylaplacian** [comment]
נשמה פתחתי אונקלוס על ק"ק טרייענז קיבלתי אולקוס
איזה שפה אתה צריך

**Comment by hezylaplacian** [comment]
לא מדבר יידיש נשמה
